-- Seed all 30 NBA teams so game FK constraints succeed.
-- Abbreviations match ESPN API output (e.g. GS not GSW, WSH not WAS, NY not NYK, SA not SAS, NO not NOP).
INSERT INTO teams (abbrev, name, conference, division) VALUES
  ('ATL', 'Atlanta Hawks',          'Eastern', 'Southeast'),
  ('BOS', 'Boston Celtics',         'Eastern', 'Atlantic'),
  ('BKN', 'Brooklyn Nets',          'Eastern', 'Atlantic'),
  ('CHA', 'Charlotte Hornets',      'Eastern', 'Southeast'),
  ('CHI', 'Chicago Bulls',          'Eastern', 'Central'),
  ('CLE', 'Cleveland Cavaliers',    'Eastern', 'Central'),
  ('DAL', 'Dallas Mavericks',       'Western', 'Southwest'),
  ('DEN', 'Denver Nuggets',         'Western', 'Northwest'),
  ('DET', 'Detroit Pistons',        'Eastern', 'Central'),
  ('GS',  'Golden State Warriors',  'Western', 'Pacific'),
  ('HOU', 'Houston Rockets',        'Western', 'Southwest'),
  ('IND', 'Indiana Pacers',         'Eastern', 'Central'),
  ('LAC', 'LA Clippers',            'Western', 'Pacific'),
  ('LAL', 'Los Angeles Lakers',     'Western', 'Pacific'),
  ('MEM', 'Memphis Grizzlies',      'Western', 'Southwest'),
  ('MIA', 'Miami Heat',             'Eastern', 'Southeast'),
  ('MIL', 'Milwaukee Bucks',        'Eastern', 'Central'),
  ('MIN', 'Minnesota Timberwolves', 'Western', 'Northwest'),
  ('NO',  'New Orleans Pelicans',   'Western', 'Southwest'),
  ('NY',  'New York Knicks',        'Eastern', 'Atlantic'),
  ('OKC', 'Oklahoma City Thunder',  'Western', 'Northwest'),
  ('ORL', 'Orlando Magic',          'Eastern', 'Southeast'),
  ('PHI', 'Philadelphia 76ers',     'Eastern', 'Atlantic'),
  ('PHX', 'Phoenix Suns',           'Western', 'Pacific'),
  ('POR', 'Portland Trail Blazers', 'Western', 'Northwest'),
  ('SAC', 'Sacramento Kings',       'Western', 'Pacific'),
  ('SA',  'San Antonio Spurs',      'Western', 'Southwest'),
  ('TOR', 'Toronto Raptors',        'Eastern', 'Atlantic'),
  ('UTA', 'Utah Jazz',              'Western', 'Northwest'),
  ('UTAH', 'Utah Jazz',             'Western', 'Northwest'),
  ('WSH', 'Washington Wizards',     'Eastern', 'Southeast')
ON CONFLICT (abbrev) DO NOTHING;
